services:
  db:
    image: postgres:latest
    container_name: expense-tracker-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - expense-tracker-data:/var/lib/mysql
    ports:
      - "5433:5432"

volumes:
  expense-tracker-data: