services:
  node:
    image: node:22-alpine
    user: node
    volumes:
      - .:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: sh -c "npm install && npm run dev"
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ipritcore-data:/var/lib/mysql
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  ipritcore-data:
