services:
  db:
    image: mysql:8.0
    container_name: pet-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - pet-data:/var/lib/mysql
    ports:
      - "3309:3306"

volumes:
  pet-data: