services:
  db:
    image: postgres:latest
    container_name: uang-kemana
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - uang-kemana-data:/var/lib/mysql
    ports:
      - "5432:5432"

volumes:
  uang-kemana-data: